

  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: password123
    bucket: file

  file:
    client-path: /file
    storage-location: D:\\uploadFile\\
    base-uri: http://localhost:${server.port}${file.client-path}

  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:9999/realms/ite-ecommerce
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 20MB

    datasource:
      driver-class-name: org.postgresql.Driver
      url: ${url}
      username: ${username}
      password: ${password}
    application:
      name: DataJpa
  server:
    port: 8088
  keycloak:
    realm: master
    server-url: http://localhost:9999
    client-id: ite-ecommerce-spring-api
    client-secret: VMhMDwB8X1jvkK5KV64Ymofnokm0FSr3
    target-realm: ite-ecommerce